# fly.toml app configuration file generated for linebot-ltc on 2024-06-11T11:02:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linebot-ltc'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
